CREATE TABLE IF NOT EXISTS GCPDB.ORDERS(
    ID INT AUTO_INCREMENT,
    MEMBER_ID LONG,
    ADDRESS_ID LONG,
    TOTAL_PRICE DOUBLE,
    TOTAL_SHIPPING DOUBLE,
    TOTAL_TAX DOUBLE,
    TOTAL_SHIPPING_TAX DOUBLE,
    CURRENCY VARCHAR(5),
    STATUS VARCHAR(3),
    TIME_PLACED DATE,
    TIME_UPDATE DATE,
    DISCOUNT DOUBLE,
    EMAIL VARCHAR(255),    
    PRIMARY KEY (ID)
);

ALTER TABLE GCPDB.ORDERS AUTO_INCREMENT=3001;


CREATE TABLE IF NOT EXISTS GCPDB.ORDERITEMS(
    ID INT AUTO_INCREMENT,
    ORDERS_ID INT,
    MEMBER_ID LONG,
    ADDRESS_ID LONG,
    PRODUCT_ID VARCHAR(255),
    PRICE DOUBLE,
    SHIPPING_CHARGE DOUBLE,
    TAX DOUBLE,
    SHIPPING_TAX DOUBLE,
    CURRENCY VARCHAR(5),
    QUANTITY LONG,
    STATUS VARCHAR(3),
    TIME_PLACED DATE,
    TIME_UPDATE DATE,
    PRODUCTDESCRIPTION VARCHAR(255),
    IMAGEURL VARCHAR(255),
    FULLFILLMENTTYPE VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDERS_ID) REFERENCES GCPDB.ORDERS(ID)
);


ALTER TABLE GCPDB.ORDERITEMS AUTO_INCREMENT=4001;

commit;

CREATE TABLE IF NOT EXISTS GCPDB.ORDERSDEMO(
    ID INT AUTO_INCREMENT,
	TOTAL_PRICE DOUBLE,
    STATUS VARCHAR(3),
    PRODUCT_ID VARCHAR(100),
    QUANTITY INT(3),
    TIME_PLACED DATE,
    TIME_UPDATE DATE,
    PRIMARY KEY (ID)
);
ALTER TABLE GCPDB.ordersdemo add quantity int(3);

select * from GCPDB.ordersdemo;

select * from GCPDB.inventory;

select * from paymentdetails;

insert into inventory values(1, 'RH_CHK_BL', 10);

ALTER TABLE GCPDB.inventory drop price;