CREATE TABLE IF NOT EXISTS GCPDB.ORDERSDEMO(
    ID INT AUTO_INCREMENT,
	TOTAL_PRICE DOUBLE,
    STATUS VARCHAR(3),
    PRODUCT_ID VARCHAR(100),
    QUANTITY INT(3),
    TIME_PLACED DATE,
    TIME_UPDATE DATE,
    PRIMARY KEY (ID)
);